import type { GuideScreen } from "./model";

/**
 * Every control in the dashboard, what it does, and what it demonstrates.
 *
 * Two pseudo-screens come first. "global" is the chrome present on every screen. "shared" holds
 * the filters that mean the same thing wherever they appear, so they are described once and
 * listed by the screens that use them rather than copied five times.
 */
export const GUIDE: readonly GuideScreen[] = [
  {
    id: "global",
    title: "On every screen",
    routePattern: "*",
    chrome: true,
    purpose: "The chrome that carries state between screens and shows where the numbers came from.",
    readsParams: ["period"],
    reachedBy: ["Always visible."],
    concepts: ["period", "provenance-chain"],
    controls: [
      {
        id: "period",
        label: "Period",
        kind: "select",
        does: "Writes the period into the address bar, and every query on the screen refetches for that submission cycle. Choosing Latest removes the parameter and lets the API decide what current means.",
        demonstrates:
          "Supervision happens per submission cycle. A finding only means something against the period whose data produced it, which is why the period is global state rather than a filter on one screen.",
        writesParams: [{ param: "period", values: "latest | YYYY-MM", clearedAt: "latest" }],
        concepts: ["period"],
        trap: {
          summary: "The period is global and it follows you between screens.",
          symptom: "A screen says no entities were scored, a minute after the portfolio looked full.",
          fix: "The selected period has no completed analysis. Set it back to Latest, or run the analysis from the ingestion screen.",
        },
      },
      {
        id: "nav",
        label: "Primary navigation",
        kind: "nav-link",
        does: "Moves between the ten screens, carrying the whole query string with it, so the period and any filter you set survive the jump.",
        demonstrates: "The screens are one investigation seen from different angles, not ten separate tools.",
      },
      {
        id: "nav-toggle",
        label: "Collapse navigation",
        kind: "button",
        does: "Shrinks the rail and replaces each label with its first letter. It is not remembered, so a reload brings the labels back.",
        demonstrates: "Room for the wide tables on the peer and audit screens. Nothing about the analysis changes.",
      },
      {
        id: "provenance",
        label: "Version, code hash, config hash and last run",
        kind: "link",
        navigatesTo: "/audit",
        does: "Opens the audit log, keeping the current query string.",
        demonstrates:
          "Every number on screen was produced by one specific version of the code and one specific configuration. This chip is the shortest path from a result back to its provenance.",
        concepts: ["provenance-chain"],
      },
      {
        id: "help",
        label: "Help for this screen",
        kind: "button",
        does: "Opens a panel describing every control on the screen you are looking at, with a Show me button that points at each one.",
        demonstrates: "The explanation lives next to the thing it explains rather than in a document you have to go and find.",
        keys: [{ keys: "Shift + /", when: "anywhere outside a text field", description: "Open or close the help panel" }],
      },
    ],
  },

  {
    id: "shared",
    title: "Filters that appear on several screens",
    routePattern: "*",
    chrome: true,
    purpose: "Controls with the same meaning wherever they appear.",
    readsParams: ["sector", "entity", "decision", "dimension", "status", "metric"],
    reachedBy: ["Wherever the screen offers them."],
    controls: [
      {
        id: "sector",
        label: "Sector",
        kind: "select",
        does: "Restricts the screen to entities in one sector.",
        demonstrates:
          "Sector is the first cut of a peer group, so filtering by it is also how you see whether a weakness is one entity's problem or the sector's.",
        writesParams: [{ param: "sector", values: "power | banking | telecom | oil_gas | transport | govt | health", clearedAt: "" }],
        concepts: ["peer-group"],
      },
      {
        id: "entity",
        label: "Entity",
        kind: "select",
        does: "Restricts the screen to one entity, or on the peer screen marks that entity on the distribution instead of filtering it.",
        demonstrates: "The same filter narrows a list or highlights a position, depending on whether the screen is a list or a comparison.",
        writesParams: [{ param: "entity", clearedAt: "" }],
        trap: {
          summary: "Filters persist across screens because they live in the address bar.",
          symptom: "The review queue looks empty right after you visited a single entity's findings.",
          fix: "Set Entity back to All. The parameter disappears from the address bar when you do.",
        },
      },
      {
        id: "decision",
        label: "Decision",
        kind: "select",
        does: "Shows only findings the tool flagged, only the ones it refused to decide, or only the ones it cleared.",
        demonstrates:
          "Three outcomes, not two. Uncertain is a decision the tool declines to make, and it is the one an examiner most needs to see.",
        writesParams: [{ param: "decision", values: "AUTO_FLAG | MANUAL_REVIEW | AUTO_CLEAR", clearedAt: "" }],
        concepts: ["uncertainty-band", "t-star"],
      },
      {
        id: "dimension",
        label: "Dimension",
        kind: "select",
        does: "Shows only findings belonging to one of the six risk dimensions.",
        demonstrates: "The dimension a finding belongs to is what connects it to the risk score, so the score can always be taken apart.",
        writesParams: [{ param: "dimension", values: "one of the six dimension keys", clearedAt: "" }],
        concepts: ["sri"],
      },
      {
        id: "status",
        label: "Status",
        kind: "select",
        does: "Open hides anything cleared or already decided by a reviewer. Reviewed shows only what has been accepted or rejected. Uncertain shows only what sits inside the decision band.",
        demonstrates: "Review state is separate from the tool's own decision, so an examiner can see what is left rather than what was raised.",
        writesParams: [{ param: "status", values: "open | reviewed | uncertain", clearedAt: "" }],
      },
      {
        id: "metric",
        label: "Metric",
        kind: "select",
        does: "Chooses which feature the peer distribution is drawn for.",
        demonstrates: "Peer comparison is per metric. An entity can sit at the median on volume and at the first percentile on escalation.",
        writesParams: [{ param: "metric", values: "a feature key", clearedAt: "escalation_ratio_critical" }],
        concepts: ["peer-group"],
      },
    ],
  },

  {
    id: "portfolio",
    title: "Portfolio overview",
    routePattern: "/portfolio",
    navKey: "portfolio",
    purpose: "Which entities need supervisory attention first, and why.",
    readsParams: ["period", "sector", "lens"],
    reachedBy: ["The first item in the navigation.", "The landing screen: the root path redirects here."],
    sharedControls: ["shared.sector"],
    concepts: ["sri", "priority-rank", "uncertainty-band"],
    controls: [
      {
        id: "lens-sri",
        label: "Risk dimensions",
        kind: "toggle",
        does: "Re-columns the heatmap as the six dimensions the risk score is built from.",
        demonstrates: "The score is never a black box. Its six parts are the default way of reading the portfolio.",
        writesParams: [{ param: "lens", values: "sri", clearedAt: "sri" }],
        concepts: ["sri"],
      },
      {
        id: "lens-capability",
        label: "Capability areas",
        kind: "toggle",
        does: "Re-columns the same rows as the eight capability areas, and a cell click then filters the entity by capability rather than by dimension.",
        demonstrates:
          "Capability framing maps findings onto what a security operations centre is supposed to be able to do, which is the language a supervisory letter is written in.",
        writesParams: [{ param: "lens", values: "capability" }],
      },
      {
        id: "tile-entities",
        label: "Entities scored",
        kind: "readout",
        availability: "requires-data",
        requires: "the period summary has loaded",
        does: "Counts the entities with a completed analysis for this period.",
        demonstrates: "An entity missing from this count submitted nothing, or its submission failed validation. Both are supervisory signals.",
      },
      {
        id: "tile-high-risk",
        label: "High or critical",
        kind: "readout",
        availability: "requires-data",
        requires: "the period summary has loaded",
        does: "Counts entities scoring 50 or above, with the change since the previous period.",
        demonstrates: "The direction matters more than the level. Three entities improving is a different portfolio from three entities deteriorating.",
        concepts: ["sri"],
      },
      {
        id: "tile-open",
        label: "Open findings",
        kind: "link",
        navigatesTo: "/findings",
        availability: "requires-data",
        requires: "the period summary has loaded",
        does: "Opens the findings list filtered to everything still awaiting a decision for this period.",
        demonstrates: "Open means neither cleared by the tool nor decided by a reviewer. It is the actual outstanding workload.",
      },
      {
        id: "tile-uncertain",
        label: "Uncertain",
        kind: "link",
        navigatesTo: "/findings",
        availability: "requires-data",
        requires: "the period summary has loaded",
        does: "Opens the findings list filtered to the decisions the tool refused to make.",
        demonstrates:
          "The honest measure of how much human work the period needs. A tool that reported no uncertainty would be hiding it, not avoiding it.",
        concepts: ["uncertainty-band", "t-star"],
      },
      {
        id: "tile-dq",
        label: "Data-quality failures",
        kind: "link",
        navigatesTo: "/ingestion",
        availability: "requires-data",
        requires: "the period summary has loaded",
        does: "Opens the ingestion screen for this period.",
        demonstrates:
          "An entity that cannot produce clean records is telling you something about its operation. Data quality is evidence here, not plumbing.",
      },
      {
        id: "heatmap",
        label: "Entity risk heatmap",
        kind: "chart",
        availability: "requires-data",
        requires: "at least one entity has been scored for this period",
        does: "Lists entities in supervisory priority order, one row each, with a cell per dimension or capability. Every cell prints its number as well as its colour.",
        demonstrates:
          "Colour is never the only cue, so the ranking survives greyscale printing and colour-vision deficiency. The row order is priority, not score.",
        concepts: ["priority-rank", "sri"],
      },
      {
        id: "heatmap-cell",
        label: "A heatmap cell",
        kind: "table-cell",
        availability: "requires-data",
        revealedBy: "portfolio.heatmap",
        navigatesTo: "/entities/:entityId",
        requires: "the heatmap has rendered",
        does: "Opens that entity with the clicked column already applied as a filter, so its findings list arrives narrowed to what you clicked.",
        demonstrates: "Drill-down carries context. You never lose the reason you clicked.",
        writesParams: [
          { param: "dimension", values: "under the risk-dimension lens" },
          { param: "capability", values: "under the capability lens" },
        ],
      },
      {
        id: "queue-preview",
        label: "Prioritised review queue",
        kind: "table",
        availability: "requires-data",
        requires: "at least one open finding exists for this period",
        does: "Shows the ten findings with the highest expected cost, and a row click opens that finding.",
        demonstrates: "The top of this list is where the next hour of examiner time is worth the most in the whole portfolio.",
        concepts: ["expected-cost"],
      },
      {
        id: "see-all-findings",
        label: "See all findings",
        kind: "link",
        navigatesTo: "/findings",
        does: "Opens the full findings list for this period, filtered to open items.",
        demonstrates: "The preview is the top of a list, not the whole of it.",
      },
    ],
  },

  {
    id: "entity",
    title: "Entity detail",
    routePattern: "/entities/:entityId",
    purpose: "Why this entity scores what it scores, and what the evidence is.",
    readsParams: ["period", "dimension", "capability", "decision", "status", "metric"],
    reachedBy: [
      "A heatmap cell on the portfolio.",
      "An entity link on the peer, coverage or review-queue screens.",
      "The breadcrumb on a finding.",
    ],
    sharedControls: ["shared.dimension", "shared.decision", "shared.status", "shared.metric"],
    concepts: ["sri", "support", "peer-group"],
    controls: [
      {
        id: "sri-table",
        label: "Supervisory Risk Indicator scorecard",
        kind: "table",
        availability: "requires-data",
        requires: "the entity has been scored for this period",
        does: "Shows each dimension's score, its weight, and the product of the two, with a Total row that adds up to the score in the heading.",
        demonstrates:
          "The score is a weighted sum you can check by hand. Nothing is hidden in a model, and the drivers column names the sub-indicators behind each dimension with their peer percentile.",
        concepts: ["sri", "support"],
      },
      {
        id: "sri-row",
        label: "A dimension row",
        kind: "table-row",
        availability: "requires-data",
        revealedBy: "entity.sri-table",
        requires: "the scorecard has rendered",
        does: "Filters the findings table below to that dimension. Clicking the same row again clears the filter.",
        demonstrates: "The link from a number to the evidence behind it is one click, in both directions.",
        writesParams: [{ param: "dimension", clearedAt: "" }],
      },
      {
        id: "weights-link",
        label: "Weights hash and edit",
        kind: "link",
        navigatesTo: "/config",
        availability: "requires-data",
        requires: "the entity has been scored",
        does: "Opens the configuration screen, and shows the hash of the weights that produced this scorecard.",
        demonstrates: "The weights are a policy choice, recorded with every run so a past score can be reproduced under the weights it was computed with.",
        concepts: ["provenance-chain"],
      },
      {
        id: "peer-chart",
        label: "Peer position",
        kind: "chart",
        availability: "requires-data",
        requires: "peer baselines exist for the selected metric",
        does: "Plots every peer on one axis for the chosen metric and marks this entity.",
        demonstrates: "A raw value means little. Where it sits among comparable entities is the supervisory question.",
        concepts: ["peer-group"],
      },
      {
        id: "data-quality",
        label: "Data quality",
        kind: "panel",
        availability: "requires-data",
        requires: "the entity submitted for this period",
        does: "Reports the rows submitted and the share that raised validation errors or warnings.",
        demonstrates: "Validation results are supervisory evidence. An entity whose records will not parse is a finding of its own.",
      },
      {
        id: "trend",
        label: "Risk indicator over time",
        kind: "chart",
        availability: "requires-data",
        requires: "the entity has been scored in more than one period",
        does: "Draws this entity's score across every period it has been scored in.",
        demonstrates: "One period is a snapshot. A weakness that appears in period three and persists is a different matter from a single bad month.",
      },
      {
        id: "headline-metrics",
        label: "Key metrics against peers",
        kind: "table",
        availability: "requires-data",
        requires: "features have been built for this entity and period",
        does: "Lists the headline features with the entity's value, the peer median, and a bar marking where the value falls in the peer range.",
        demonstrates: "Thin metrics carry a support marker, because a median over six alerts is not evidence and the screen should say so.",
        concepts: ["support", "peer-group"],
      },
      {
        id: "controls",
        label: "Control priorities",
        kind: "panel",
        availability: "requires-data",
        requires: "at least one finding is attributed to a control",
        does: "Groups this entity's findings by the control they implicate and sums the expected cost of each group.",
        demonstrates: "Supervisory action is taken against a control, not against a finding. This is the list a remediation letter is written from.",
        concepts: ["expected-cost"],
      },
      {
        id: "findings",
        label: "Findings table",
        kind: "table",
        availability: "requires-data",
        requires: "the entity has findings in this period",
        does: "Lists this entity's findings, filtered by whatever the four selects above are set to, and a row opens the finding.",
        demonstrates: "Every score on this screen resolves to a list of named findings, each of which resolves to evidence.",
      },
      {
        id: "findings-first-row",
        label: "The highest-priority finding",
        kind: "table-row",
        availability: "requires-data",
        revealedBy: "entity.findings",
        navigatesTo: "/findings/:findingId",
        requires: "the entity has at least one finding matching the filters",
        does: "Opens that finding with its rationale, evidence and the raw alerts behind it.",
        demonstrates: "The table is sorted by priority, so the top row is where this entity's supervisory attention should start.",
      },
      {
        id: "export-pdf",
        label: "Export PDF",
        kind: "button",
        does: "Downloads a report for this entity and period, and records the export in the audit log.",
        demonstrates: "The exported document carries the code, configuration and model versions that produced it, so it can be defended later.",
        concepts: ["provenance-chain"],
      },
      {
        id: "export-csv",
        label: "Export findings CSV",
        kind: "button",
        does: "Downloads this entity's findings for the period as a spreadsheet.",
        demonstrates: "Findings leave the tool in a form a supervisor can work with elsewhere.",
      },
    ],
  },

  {
    id: "findings",
    title: "Findings",
    routePattern: "/findings",
    navKey: "findings",
    purpose: "Every supervisory indicator raised for the period, in one filterable list.",
    readsParams: ["period", "entity", "decision", "dimension", "status"],
    reachedBy: ["The navigation.", "The open-findings and uncertain tiles on the portfolio.", "The See all findings link."],
    sharedControls: ["shared.entity", "shared.dimension", "shared.decision", "shared.status"],
    controls: [
      {
        id: "table",
        label: "Findings table",
        kind: "table",
        availability: "requires-data",
        requires: "the period has a completed analysis",
        does: "Lists every finding matching the filters, sortable by any column, and a row opens the finding.",
        demonstrates:
          "The whole portfolio's findings in one place, so a pattern that crosses entities, one rule firing everywhere, is visible.",
      },
      {
        id: "row",
        label: "A finding row",
        kind: "table-row",
        availability: "requires-data",
        revealedBy: "findings.table",
        navigatesTo: "/findings/:findingId",
        requires: "at least one finding matches the filters",
        does: "Opens that finding with its rationale, evidence and raw records.",
        demonstrates: "Two clicks from the portfolio to a named finding, three to the alerts underneath it.",
      },
    ],
  },

  {
    id: "finding",
    title: "Finding detail",
    routePattern: "/findings/:findingId",
    purpose: "Why this finding was raised, what it rests on, and whether the examiner agrees.",
    readsParams: ["period", "tab"],
    reachedBy: ["A row in any findings table.", "The review queue.", "A coverage cell's related finding."],
    concepts: ["t-star", "uncertainty-band", "calibration", "expected-cost"],
    controls: [
      {
        id: "decision-badge",
        label: "Decision badge",
        kind: "badge",
        does: "States whether the tool flagged, cleared or refused to decide this finding, and on hover gives the probability, the threshold and the band.",
        demonstrates:
          "A decision is only meaningful with the threshold it was taken against. Both are shown together so neither can be quoted without the other.",
        concepts: ["t-star", "uncertainty-band"],
      },
      {
        id: "rationale",
        label: "Rationale",
        kind: "readout",
        does: "States in one paragraph what was observed, with the numbers that triggered it and the peer values they are being compared against.",
        demonstrates: "A finding an examiner cannot read aloud to the entity is not usable. The rationale is written to be quoted.",
      },
      {
        id: "score-line",
        label: "Probability, calibration and expected cost",
        kind: "readout",
        does: "Shows the final probability, the rule and model probabilities behind it, whether the model probability is calibrated, and the cost of missing this finding.",
        demonstrates:
          "A rule finding says so rather than claiming calibration it never needed. An uncalibrated model score says so too, instead of dressing a rank up as a probability.",
        concepts: ["calibration", "expected-cost"],
      },
      {
        id: "threshold",
        label: "Threshold line",
        kind: "chart",
        does: "Draws the zero-to-one scale with the threshold, the uncertainty band around it, and this finding's probability marked on it.",
        demonstrates: "The decision is a position on a line, not a verdict. You can see how close to the boundary it fell.",
        concepts: ["t-star", "uncertainty-band"],
      },
      {
        id: "feedback",
        label: "Accept, Reject and Defer",
        kind: "button",
        does: "Records the examiner's decision with an optional comment, appends it to the history below, and feeds the calibration that turns model scores into probabilities.",
        demonstrates:
          "The tool is an aid, not an authority. Human decisions are recorded, never overwritten, and are what the model learns from.",
        keys: [
          { keys: "A", when: "focus anywhere in the feedback bar except the comment box", description: "Accept" },
          { keys: "R", when: "focus anywhere in the feedback bar except the comment box", description: "Reject" },
          { keys: "D", when: "focus anywhere in the feedback bar except the comment box", description: "Defer, which needs a comment" },
        ],
        trap: {
          summary: "The shortcuts are bar-wide, not per button.",
          symptom: "You press A while the Reject button has focus and an accept is recorded.",
          fix: "A always means accept anywhere in the bar. Decisions are append-only and the latest wins, so recording the opposite decision corrects it.",
        },
        concepts: ["calibration"],
      },
      {
        id: "tab-evidence",
        label: "Evidence tab",
        kind: "tab",
        does: "Shows each feature behind the finding with the entity's value, the peer median, the tenth to ninetieth percentile range, and the standardised distance from the median.",
        demonstrates: "Evidence is comparative. The number alone proves nothing until you see what comparable entities look like.",
        writesParams: [{ param: "tab", values: "evidence", clearedAt: "evidence" }],
        concepts: ["peer-group"],
      },
      {
        id: "tab-explanation",
        label: "Explanation tab",
        kind: "tab",
        does: "Shows the rule that fired with its template, its parameters and the values it was evaluated on, and for model findings the per-feature attribution.",
        demonstrates:
          "For a rule you can read the exact condition and check the arithmetic. For a model you get the contributions and what would have to change for the decision to flip.",
        writesParams: [{ param: "tab", values: "explanation" }],
      },
      {
        id: "attribution-row",
        label: "A model attribution row",
        kind: "button",
        availability: "in-tab",
        requires: "the explanation tab is open and the finding involved a model",
        revealedBy: "finding.tab-explanation",
        does: "Switches to the evidence tab, selects that feature and scrolls it into view. Features with no peer comparison are disabled rather than dead.",
        demonstrates: "An attribution is a claim about a feature. Clicking it takes you to the evidence for that claim.",
      },
      {
        id: "tab-records",
        label: "Raw records tab",
        kind: "tab",
        does: "Lists the individual alerts behind the finding, sortable, paginated, and a row opens the original record including the line it came from in the submitted file.",
        demonstrates: "Three clicks from the portfolio to the actual alerts. Nothing is asserted that cannot be traced to a submitted row.",
        writesParams: [{ param: "tab", values: "records" }],
      },
    ],
  },

  {
    id: "queue",
    title: "Review queue",
    routePattern: "/queue",
    navKey: "queue",
    purpose: "What to examine next, and in what order.",
    readsParams: ["period", "scope", "entity", "sector", "decision"],
    reachedBy: ["The navigation."],
    sharedControls: ["shared.entity", "shared.sector", "shared.decision"],
    concepts: ["expected-cost", "uncertainty-band"],
    controls: [
      {
        id: "scope-sample",
        label: "Alert samples",
        kind: "toggle",
        does: "Shows individual alerts selected for manual inspection, ranked, with the rules that flagged each one.",
        demonstrates:
          "Sampling is round-robin across rules rather than straight down the score, so every kind of weakness is represented instead of the loudest one filling the list.",
        writesParams: [{ param: "scope", values: "sample", clearedAt: "sample" }],
      },
      {
        id: "scope-entity",
        label: "Entity findings",
        kind: "toggle",
        does: "Switches the same screen to entity-level findings awaiting review.",
        demonstrates: "The same queue at a different grain. An examiner works either alert by alert or entity by entity.",
        writesParams: [{ param: "scope", values: "entity" }],
      },
      {
        id: "scope-control",
        label: "Controls and processes",
        kind: "toggle",
        does: "Groups findings by the control they implicate and sums the expected cost of each group.",
        demonstrates:
          "The most useful supervisory output is often not an entity but a process: the control failing across several entities at once.",
        writesParams: [{ param: "scope", values: "control" }],
        concepts: ["expected-cost"],
      },
      {
        id: "table",
        label: "Queue table",
        kind: "table",
        availability: "requires-data",
        requires: "the period has a completed analysis",
        does: "Lists queued alerts in rank order with severity, category, time to close, the rules that fired, the probability and the decision.",
        demonstrates: "Rank is expected cost, so the order is where examiner time pays back most, not simply where the score is highest.",
        concepts: ["expected-cost"],
      },
      {
        id: "row",
        label: "A queue row",
        kind: "table-row",
        availability: "requires-data",
        revealedBy: "queue.table",
        requires: "at least one alert is queued",
        does: "Opens a panel with the alert, why it was queued, its investigation note, any alerts closed with an identical note, and a feedback bar.",
        demonstrates: "Everything needed to judge one alert in one panel, so a reviewer never has to leave the queue to make a decision.",
      },
      {
        id: "drawer-feedback",
        label: "Feedback inside the preview panel",
        kind: "button",
        availability: "in-drawer",
        requires: "a queue row is open",
        revealedBy: "queue.row",
        does: "Records accept, reject or defer against the alert without leaving the queue.",
        demonstrates: "Review is a sequence. The panel is designed to be worked down, not opened and closed one finding at a time.",
      },
    ],
  },

  {
    id: "peer",
    title: "Peer benchmarking",
    routePattern: "/peer",
    navKey: "peer",
    purpose: "Where an entity sits among comparable entities, metric by metric.",
    readsParams: ["period", "metric", "entity", "sector"],
    reachedBy: ["The navigation."],
    sharedControls: ["shared.metric", "shared.entity", "shared.sector"],
    concepts: ["peer-group"],
    controls: [
      {
        id: "chart",
        label: "Distribution across peers",
        kind: "chart",
        availability: "requires-data",
        requires: "peer baselines exist for this metric and period",
        does: "Plots every entity in the peer group for the chosen metric, marks the median and the tenth to ninetieth percentile range, and highlights the selected entity.",
        demonstrates:
          "Comparisons use the median and the median absolute deviation, not the mean, so one extreme entity cannot drag the baseline it is being judged against.",
        concepts: ["peer-group"],
      },
      {
        id: "chart-mark",
        label: "An entity marker",
        kind: "chart",
        availability: "requires-data",
        revealedBy: "peer.chart",
        requires: "the distribution has rendered",
        // Points are drawn by the charting library inside an SVG, so there is no stable element
        // to anchor. It is described here and spotlit via the chart that contains it.
        undocumentedInDom: true,
        does: "Selects that entity, highlighting it on the chart and naming its value against the median in the line below.",
        demonstrates: "The chart is a control, not a picture.",
        writesParams: [{ param: "entity", clearedAt: "" }],
      },
      {
        id: "peer-level",
        label: "Peer group and level",
        kind: "readout",
        availability: "requires-data",
        requires: "the distribution has loaded",
        does: "Names the peer group used, how it was chosen, and how many entities are in it.",
        demonstrates:
          "When too few entities share a sector and size the group widens, and the screen says so. A comparison against three peers is worth less than one against thirty, and it should not be able to hide that.",
        concepts: ["peer-group", "support"],
      },
      {
        id: "rank-table",
        label: "Rank table",
        kind: "table",
        availability: "requires-data",
        requires: "the period has a completed analysis",
        does: "Lists every entity against the headline metrics, colouring a value when it falls in the risky quarter of its peer group.",
        demonstrates: "One row per entity across many metrics, which is where an entity that is unremarkable everywhere but bad in one place becomes visible.",
      },
    ],
  },

  {
    id: "coverage",
    title: "Negative space",
    routePattern: "/coverage",
    navKey: "coverage",
    purpose: "Evidence a supervisor would expect to see and does not.",
    readsParams: ["period", "dimension", "sector"],
    reachedBy: ["The navigation."],
    sharedControls: ["shared.sector"],
    concepts: ["negative-space", "peer-group"],
    controls: [
      {
        id: "dimension-category",
        label: "Alert categories",
        kind: "toggle",
        does: "Draws the matrix with one column per alert category the entity is expected to report.",
        demonstrates: "An entity that never reports lateral movement is either not seeing it or not detecting it. Both need explaining.",
        writesParams: [{ param: "dimension", values: "category", clearedAt: "category" }],
      },
      {
        id: "dimension-asset",
        label: "Asset classes",
        kind: "toggle",
        does: "Redraws the matrix with one column per class of asset.",
        demonstrates: "Coverage that looks complete by category can still have a whole class of asset producing nothing.",
        writesParams: [{ param: "dimension", values: "asset_class" }],
      },
      {
        id: "dimension-source",
        label: "Telemetry sources",
        kind: "toggle",
        does: "Redraws the matrix with one column per telemetry source.",
        demonstrates: "A source that stopped reporting is the earliest visible sign of a monitoring gap.",
        writesParams: [{ param: "dimension", values: "source" }],
      },
      {
        id: "legend",
        label: "Legend",
        kind: "readout",
        does: "Explains the four cell states: reported at the expected level, reported but below the peer tenth percentile, expected but entirely absent, and not expected.",
        demonstrates: "Absent cells are hatched and carry text, never colour alone, so the matrix survives printing and colour-vision deficiency.",
      },
      {
        id: "matrix",
        label: "Coverage matrix",
        kind: "table",
        availability: "requires-data",
        requires: "the period has a completed analysis",
        does: "One row per entity, one column per expected item, with counts of absent items down the right edge and across the bottom.",
        demonstrates:
          "The totals are the point. A column absent for most entities is a sector problem; a row with many absences is one entity's blind spot.",
        concepts: ["negative-space"],
      },
      {
        id: "matrix-cell",
        label: "A matrix cell",
        kind: "button",
        availability: "requires-data",
        revealedBy: "coverage.matrix",
        requires: "the matrix has rendered",
        does: "Opens a panel giving the observed count, the peer median, and why this item was expected at all.",
        demonstrates:
          "Expectation is derived, not assumed: from the entity's own asset inventory, from its sector, and from what its peers actually report. The panel states which.",
        concepts: ["negative-space", "peer-group"],
      },
    ],
  },

  {
    id: "trends",
    title: "Trends",
    routePattern: "/trends",
    navKey: "trends",
    purpose: "How supervisory risk moves across periods.",
    readsParams: ["period", "sector", "entity"],
    reachedBy: ["The navigation."],
    sharedControls: ["shared.sector"],
    controls: [
      {
        id: "entity-select",
        label: "Entity detail",
        kind: "select",
        does: "Adds a second chart breaking one entity's score into its six dimensions across every period.",
        demonstrates: "A flat overall score can hide one dimension deteriorating while another improves.",
        writesParams: [{ param: "entity", clearedAt: "" }],
        concepts: ["sri"],
      },
      {
        id: "sri-chart",
        label: "Risk indicator by entity",
        kind: "chart",
        availability: "requires-data",
        requires: "at least two periods have completed analyses",
        does: "Draws up to six entities against the dashed sector median.",
        demonstrates: "Against a rising median, a flat entity is falling behind. The comparison line is what makes a trend readable.",
      },
      {
        id: "controls-chart",
        label: "Control priorities over time",
        kind: "chart",
        availability: "requires-data",
        requires: "at least two periods have completed analyses",
        does: "Draws the total expected cost attributed to each control, per period.",
        demonstrates: "Which processes are failing across the whole portfolio, and whether supervisory attention has moved them.",
        concepts: ["expected-cost"],
      },
    ],
  },

  {
    id: "ingestion",
    title: "Ingestion and data quality",
    routePattern: "/ingestion",
    navKey: "ingestion",
    purpose: "Getting submissions in, seeing what was wrong with them, and running the analysis.",
    readsParams: ["period"],
    reachedBy: ["The navigation.", "The data-quality tile on the portfolio."],
    controls: [
      {
        id: "upload-entity",
        label: "Entity",
        kind: "select",
        does: "Chooses which entity the files being uploaded belong to.",
        demonstrates: "Submissions are always attributed. There is no anonymous ingestion path.",
      },
      {
        id: "upload-period",
        label: "Submission period",
        kind: "text-input",
        does: "Sets the period the uploaded files belong to, written as a year and month.",
        demonstrates: "The period is declared by the submitter, and rows falling outside it are flagged rather than silently moved.",
        concepts: ["period"],
      },
      {
        id: "upload-files",
        label: "Files",
        kind: "file-input",
        does: "Selects one or more files. Comma-separated, JSON and SQLite exports are all accepted.",
        demonstrates: "Entities export from whatever their case-management system produces. Meeting them where they are is what makes the tool deployable.",
      },
      {
        id: "upload-submit",
        label: "Upload and validate",
        kind: "button",
        does: "Sends the files, runs thirteen validation checks, stores the results against the submission and reports what it found.",
        demonstrates:
          "Validation records rather than merely rejects. The error and warning rates become features, because an entity that cannot produce clean records is itself a supervisory signal.",
        trap: {
          summary: "Re-uploading an identical file does nothing.",
          symptom: "You upload the same file twice and the second one reports no new rows.",
          fix: "That is deliberate. Submissions are identified by their content hash, so ingestion is repeatable. A changed file supersedes the old one instead of duplicating it.",
        },
      },
      {
        id: "run",
        label: "Run analysis",
        kind: "button",
        does: "Starts the pipeline for the selected period and polls until it finishes, showing each stage as it completes.",
        demonstrates:
          "The tool is batch and it only runs when a person asks. There is no scheduler and no continuous collection, which is the boundary between supervision and operating a security operations centre.",
        trap: {
          summary: "Running twice on unchanged inputs is skipped, not repeated.",
          symptom: "The run finishes instantly and reports that nothing changed.",
          fix: "The pipeline is idempotent: identical inputs, configuration, code and models produce the same result, so it declines to recompute it.",
        },
      },
      {
        id: "status",
        label: "Analysis status",
        kind: "panel",
        does: "Reports the last or current run with its code and configuration hashes and a row per pipeline stage with row counts and timings.",
        demonstrates: "The pipeline is legible while it runs. A stage that is slow or empty is visible before the results are.",
        concepts: ["provenance-chain"],
      },
      {
        id: "submissions",
        label: "Submissions table",
        kind: "table",
        availability: "requires-data",
        requires: "at least one submission has been ingested",
        does: "Lists submissions with their format, row counts and error and warning rates. A row expands to show which checks fired and on which rows.",
        demonstrates: "The validation detail names the check and samples the offending rows, so a data-quality finding can be taken back to the entity with specifics.",
      },
    ],
  },

  {
    id: "config",
    title: "Configuration",
    routePattern: "/config",
    navKey: "config",
    purpose: "The policy choices the analytics depend on, and what changing them would do.",
    readsParams: ["period"],
    reachedBy: ["The navigation.", "The weights link on an entity's scorecard."],
    concepts: ["t-star", "sri", "uncertainty-band", "provenance-chain"],
    controls: [
      {
        id: "weights",
        label: "Risk indicator weights",
        kind: "number-input",
        does: "Sets each dimension's weight. The running sum is shown, and Save stays disabled until it is exactly 1.00.",
        demonstrates: "The weighting is a supervisory judgement, not a technical constant. It is editable, and it is hashed into every run that uses it.",
        concepts: ["sri"],
      },
      {
        id: "cost-cfp",
        label: "Cost of a false positive",
        kind: "number-input",
        does: "Sets what it costs to send a healthy entity for manual review, and the threshold beside it recomputes as you type.",
        demonstrates: "Raising this makes the tool more reluctant to flag, which is the correct lever when examiner time is the binding constraint.",
        concepts: ["t-star"],
      },
      {
        id: "cost-cfn",
        label: "Cost of a false negative",
        kind: "number-input",
        does: "Sets what it costs to miss a real weakness. The threshold and the band on the line below move immediately.",
        demonstrates:
          "This is where the tool's caution actually comes from. The threshold is derived from the two costs rather than picked, so a change in supervisory posture is one number, not a retuning exercise.",
        concepts: ["t-star", "uncertainty-band"],
      },
      {
        id: "threshold-line",
        label: "Threshold line",
        kind: "chart",
        does: "Draws the resulting threshold and its uncertainty band on a zero-to-one scale, for each class of finding.",
        demonstrates: "Two numbers become a picture of how much of the probability range is handed to a human.",
        concepts: ["t-star", "uncertainty-band"],
      },
      {
        id: "preview",
        label: "Preview impact",
        kind: "button",
        does: "Recomputes every entity's score under the proposed settings and reports the change, plus how many findings would become uncertain. Nothing is saved.",
        demonstrates: "A weighting change is a supervisory decision with consequences you can see before you take it.",
      },
      {
        id: "save",
        label: "Save",
        kind: "button",
        does: "Writes the configuration, produces a new configuration hash, and records the change in the audit log. Existing results are untouched until the analysis is re-run.",
        demonstrates:
          "Configuration is data, versioned like data. A past run keeps the configuration it used, so a score computed in March is still reproducible after an April policy change.",
        concepts: ["provenance-chain"],
        trap: {
          summary: "Saving does not change any result on screen.",
          symptom: "The portfolio looks identical after you change the weights and save.",
          fix: "Re-run the analysis from the ingestion screen. Findings belong to the run that produced them, and results are never rewritten in place.",
        },
      },
      {
        id: "rules",
        label: "Rules table",
        kind: "table",
        does: "Lists all nineteen rules with the control and capability each maps to, its prior weight and its parameters, and a checkbox to disable one.",
        demonstrates:
          "Rules come first and the model second. Every rule is readable here with the exact thresholds it uses, which is what makes a finding arguable rather than merely asserted.",
      },
      {
        id: "history",
        label: "Configuration history",
        kind: "table",
        does: "Lists past configuration hashes with when they were saved, by whom and why.",
        demonstrates: "Policy changes are part of the audit trail, not something that happens outside it.",
        concepts: ["provenance-chain"],
      },
    ],
  },

  {
    id: "audit",
    title: "Audit log",
    routePattern: "/audit",
    navKey: "audit",
    purpose: "What ran, on what, with which code and configuration, and whether the record has been altered.",
    readsParams: ["type"],
    reachedBy: ["The navigation.", "The provenance chip in the top bar.", "The audit link on the ingestion screen."],
    concepts: ["provenance-chain"],
    controls: [
      {
        id: "type-filter",
        label: "Run type buttons",
        kind: "toggle",
        does: "Restricts the table to one kind of event: analysis, ingestion, feedback, configuration, training, recalibration or report generation.",
        demonstrates: "Everything that touches the data is an audit event, not only the analysis. Exporting a report is recorded too.",
        writesParams: [{ param: "type", values: "PIPELINE | INGEST | FEEDBACK | CONFIG | TRAIN | RECALIBRATE | REPORT", clearedAt: "" }],
      },
      {
        id: "verify",
        label: "Verify chain",
        kind: "button",
        does: "Recomputes every run hash from the run before it and reports either that the chain is intact across all runs or the first run where it breaks.",
        demonstrates:
          "Each run's hash covers the previous run's hash, so altering any past record breaks every hash after it. This button is the proof, and it is the answer to how a finding can be defended months later.",
        concepts: ["provenance-chain"],
      },
      {
        id: "runs",
        label: "Runs table",
        kind: "table",
        availability: "requires-data",
        requires: "at least one run has been recorded",
        does: "Lists runs newest first with the code, configuration and run hashes, and a row opens the full detail.",
        demonstrates: "The hashes are the identity of a result. Two runs with the same three hashes and the same inputs must produce the same output.",
      },
      {
        id: "run-row",
        label: "A run row",
        kind: "table-row",
        availability: "requires-data",
        revealedBy: "audit.runs",
        requires: "at least one run has been recorded",
        does: "Opens a panel with the stage-by-stage timing, the input and output hashes, the previous run's hash, and the complete configuration the run used.",
        demonstrates: "The configuration snapshot is stored with the run, so a result can be re-examined under the settings it was actually computed with.",
      },
      {
        id: "models",
        label: "Model registry",
        kind: "table",
        does: "Lists every trained model version with which is active, how many rows it was trained on, its calibration metrics and its artifact hash.",
        demonstrates:
          "Models are pinned to the feature list they were trained on, and the pipeline refuses to run if the two disagree, so a stale model cannot quietly score new features.",
        concepts: ["calibration"],
      },
    ],
  },

  {
    id: "reports",
    title: "Reports",
    routePattern: "/reports",
    navKey: "reports",
    purpose: "Getting findings out of the tool in a form that can be sent, filed and defended.",
    readsParams: ["period"],
    reachedBy: ["The navigation."],
    controls: [
      {
        id: "entity-select",
        label: "Entity",
        kind: "select",
        does: "Chooses the entity the report is about.",
        demonstrates: "Reports are per entity and period, which is the unit a supervisory letter is written about.",
      },
      {
        id: "entity-pdf",
        label: "Generate PDF",
        kind: "button",
        does: "Builds a document with the scorecard arithmetic, every finding with its rationale, the alerts selected for review and the feedback recorded so far.",
        demonstrates: "The document is self-contained, so a reader without access to the tool can still follow the reasoning.",
      },
      {
        id: "entity-csv",
        label: "Findings CSV",
        kind: "button",
        does: "Downloads that entity's findings for the period as a spreadsheet.",
        demonstrates: "Findings leave in a machine-readable form as well as a readable one.",
      },
      {
        id: "portfolio-pdf",
        label: "Portfolio PDF",
        kind: "button",
        does: "Builds a period summary across every entity: the heatmap, control priorities and the counts a supervisor needs.",
        demonstrates: "The portfolio view is what a supervisory body reviews; the entity report is what it sends.",
      },
      {
        id: "portfolio-csv",
        label: "Portfolio CSV exports",
        kind: "button",
        does: "Downloads findings, scores, alert samples or the full feature table for the period.",
        demonstrates: "The feature export is what lets someone check the analytics independently rather than taking the conclusions on trust.",
      },
      {
        id: "feedback-stats",
        label: "Feedback and calibration",
        kind: "panel",
        does: "Reports how many decisions have been recorded, the accept rate per rule, and each calibrator's label count and calibration error.",
        demonstrates:
          "A rule an examiner keeps rejecting is a rule with the wrong threshold. This panel is where that becomes visible, and it is what bounded recalibration acts on.",
        concepts: ["calibration"],
      },
      {
        id: "history",
        label: "Generated reports",
        kind: "table",
        does: "Lists what was exported, when, for which entity and period.",
        demonstrates: "Exports are audit events. What left the tool is part of the record.",
        concepts: ["provenance-chain"],
      },
    ],
  },
];
